fl_joint: 0.0
fr_joint: 0.0
rl_bracket_joint: 0.0
rl_wheel_joint: 0.0
rr_bracket_joint: 0.0
rr_wheel_joint: 0.0
arm_joint_1: 0.0
arm_joint_2: 0.0
arm_joint_3: 0.0
arm_joint_4: 0.0
arm_joint_5: 0.0
arm_joint_6: 0.0
right_finger_bottom_joint: 0.0
right_finger_tip_joint: 0.0
left_finger_bottom_joint: 0.0
left_finger_tip_joint: 0.0