controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    twist_controller:
      type: picknik_twist_controller/PicknikTwistController

    robotiq_gripper_controller:
      type: position_controllers/GripperActionController
    
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
      - arm_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0
  
twist_controller:
  ros__parameters:
    joint: tcp
    interface_names:
      - twist.linear.x
      - twist.linear.y
      - twist.linear.z
      - twist.angular.x
      - twist.angular.y
      - twist.angular.z

robotiq_gripper_controller:
  ros__parameters:
    default: true
    joint: right_finger_bottom_joint
    allow_stalling: true
    min_position: -0.09
    max_position: 0.96

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["fl_joint"]
    right_wheel_names: ["fr_joint"]
    publish_limited_velocity: true
    wheel_separation: 0.255094
    wheel_radius: 0.0575
    cmd_vel_timeout: 0.25
    use_stamped_vel: false
    base_frame_id: base_link
    odom_frame_id: odom
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.5
        min_velocity: -1.5
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 0.78539816339
        min_velocity: -0.78539816339