controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_traj_cont:
      type: joint_trajectory_controller/JointTrajectoryController

    diff_drive_cont:
      type: diff_drive_controller/DiffDriveController

joint_traj_cont:
  ros__parameters:
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
      - arm_joint_6
      - right_finger_bottom_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      goal_time: 1.0
      stopped_velocity_tolerance: 0.01
      trajectory:
        arm_joint_1:
          max_velocity: 0.5
          max_acceleration: 1.0
        arm_joint_2:
          max_velocity: 0.5
          max_acceleration: 0.5
        arm_joint_3:
          max_velocity: 0.5
          max_acceleration: 0.4
        arm_joint_4:
          max_velocity: 0.5
          max_acceleration: 1.0
        arm_joint_5:
          max_velocity: 0.5
          max_acceleration: 10.0
        arm_joint_6:
          max_velocity: 0.5
          max_acceleration: 10.0
    interpolator:
      type: cubic

diff_drive_cont:
  ros__parameters:
    publish_rate: 100.0
    base_frame_id: base_link
    left_wheel_names: ['fl_joint']
    right_wheel_names: ['fr_joint']
    wheel_separation: 0.255094
    wheel_radius: 0.0575
    use_stamped_vel: false


    publish_limited_velocity: true
    cmd_vel_timeout: 0.25 # RL 알고리즘 주기에 맞게 조정
    odom_frame_id: odom
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.5
        min_velocity: -1.5
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 0.78539816339
        min_velocity: -0.78539816339
