<?xml version="1.0"?>
<robot name="d435i" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="d435_cam_depth_to_infra1_offset" value="0.0"/>
  <xacro:property name="d435_cam_depth_to_infra2_offset" value="-0.050"/>
  <xacro:property name="d435_cam_depth_to_color_offset" value="0.015"/>
  <xacro:property name="d435_cam_width" value="0.090"/>
  <xacro:property name="d435_cam_height" value="0.025"/>
  <xacro:property name="d435_cam_depth" value="0.02505"/>
  <xacro:property name="d435_cam_mount_from_center_offset" value="0.0149"/>
  <xacro:property name="d435_glass_to_front" value="0.1e-3"/>
  <xacro:property name="d435_zero_depth_to_glass" value="4.2e-3"/>
  <xacro:property name="d435_mesh_x_offset" value="${d435_cam_mount_from_center_offset-d435_glass_to_front-d435_zero_depth_to_glass}"/>
  <xacro:property name="d435_cam_depth_px" value="${d435_cam_mount_from_center_offset}"/>
  <xacro:property name="d435_cam_depth_py" value="0.0175"/>
  <xacro:property name="d435_cam_depth_pz" value="${d435_cam_height/2}"/>

  <xacro:property name="camera_width" value="1280"/>
  <xacro:property name="camera_height" value="720"/>
  <xacro:property name="camera_fps" value="30"/>
  <xacro:property name="horizontal_fov" value="${69.4 * M_PI / 180}"/>
  <xacro:property name="rgb_horizontal_fov" value="${69.4 * M_PI / 180}"/>
  <xacro:property name="depth_horizontal_fov" value="${85.2 * M_PI / 180}"/>
  
  <xacro:macro name="camera" params="
    parent
    sim_gazebo
    sim_ignition
    sim_isaac">

    <xacro:if value="${sim_isaac}">
      <joint name="${parent}_depth_joint" type="fixed">
        <origin xyz="${d435_cam_mount_from_center_offset + d435_zero_depth_to_glass - d435_cam_depth} ${d435_cam_depth_py} 0" rpy="0 0 0"/>
        <parent link="${parent}"/>
        <child link="${parent}_depth_frame" />
      </joint>
      <link name="${parent}_depth_frame">
        <inertial>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <mass value="0.01"/>
          <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
        </inertial>
        <visual>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </collision>
      </link>
    </xacro:if>
    
    <xacro:if value="${sim_gazebo or sim_ignition}">
      <joint name="${parent}_depth_joint" type="fixed">
        <origin xyz="${d435_cam_mount_from_center_offset + d435_zero_depth_to_glass - d435_cam_depth} ${d435_cam_depth_py} 0" rpy="0 0 0"/>
        <parent link="${parent}"/>
        <child link="${parent}_depth_frame" />
      </joint>
      <link name="${parent}_depth_frame"/>

      <joint name="${parent}_depth_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${parent}_depth_frame" />
        <child link="${parent}_depth_optical_frame" />
      </joint>
      <link name="${parent}_depth_optical_frame"/>
      
      <joint name="${parent}_color_joint" type="fixed">
        <origin xyz="0 ${d435_cam_depth_to_color_offset} 0" rpy="0 0 0" />
        <parent link="${parent}_depth_frame" />
        <child link="${parent}_color_frame" />
      </joint>
      <link name="${parent}_color_frame"/>

      <joint name="${parent}_color_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${parent}_color_frame" />
        <child link="${parent}_color_optical_frame" />
      </joint>
      <link name="${parent}_color_optical_frame"/>

      <joint name="${parent}_infra1_joint" type="fixed">
        <origin xyz="0 ${d435_cam_depth_to_infra1_offset} 0" rpy="0 0 0" />
        <parent link="${parent}_depth_frame" />
        <child link="${parent}_infra1_frame" />
      </joint>
      <link name="${parent}_infra1_frame"/>

      <joint name="${parent}_infra1_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${parent}_infra1_frame" />
        <child link="${parent}_infra1_optical_frame" />
      </joint>
      <link name="${parent}_infra1_optical_frame"/>

      <joint name="${parent}_infra2_joint" type="fixed">
        <origin xyz="0 ${d435_cam_depth_to_infra2_offset} 0" rpy="0 0 0" />
        <parent link="${parent}_depth_frame" />
        <child link="${parent}_infra2_frame" />
      </joint>
      <link name="${parent}_infra2_frame"/>

      <joint name="${parent}_infra2_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${parent}_infra2_frame" />
        <child link="${parent}_infra2_optical_frame" />
      </joint>
      <link name="${parent}_infra2_optical_frame"/>

      <joint name="${parent}_accel_joint" type="fixed">
        <origin xyz = "-0.01174 -0.00552 0.0051" rpy = "0 0 0" />
        <parent link="${parent}_depth_frame" />
        <child link="${parent}_accel_frame" />
      </joint>
      <link name="${parent}_accel_frame"/>

      <joint name="${parent}_accel_optical_joint" type="fixed">
        <origin xyz = "0 0 0" rpy = "${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${parent}_accel_frame" />
        <child link="${parent}_accel_optical_frame" />
      </joint>
      <link name="${parent}_accel_optical_frame"/>

      <joint name="${parent}_gyro_joint" type="fixed">
        <origin xyz = "-0.01174 -0.00552 0.0051" rpy = "0 0 0" />
        <parent link="${parent}_depth_frame" />
        <child link="${parent}_gyro_frame" />
      </joint>
      <link name="${parent}_gyro_frame"/>

      <joint name="${parent}_gyro_optical_joint" type="fixed">
        <origin xyz = "0 0 0" rpy = "${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${parent}_gyro_frame" />
        <child link="${parent}_gyro_optical_frame" />
      </joint>
      <link name="${parent}_gyro_optical_frame"/>
      
      <xacro:if value="${sim_gazebo}">
        <xacro:include filename="$(find mobile_manipulator)/urdf/gazebo_camera.xacro"/>
        <xacro:gazebo_camera
          camera_frame="${parent}"
          color_camera_optical_frame="${parent}_color_optical_frame"
          depth_camera_optical_frame="${parent}_depth_optical_frame"
          camera_width="${camera_width}"
          camera_height="${camera_height}"
          camera_fps="${camera_fps}"
          horizontal_fov="${rgb_horizontal_fov}"/>
      </xacro:if>
    </xacro:if>
  </xacro:macro>
</robot>