<?xml version="1.0"?>
<robot name="d435i" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="d435_cam_depth_to_infra1_offset" value="0.0"/>
  <xacro:property name="d435_cam_depth_to_infra2_offset" value="-0.050"/>
  <xacro:property name="d435_cam_depth_to_color_offset" value="0.015"/>
  <xacro:property name="d435_cam_width" value="0.090"/>
  <xacro:property name="d435_cam_height" value="0.025"/>
  <xacro:property name="d435_cam_depth" value="0.02505"/>
  <xacro:property name="d435_cam_mount_from_center_offset" value="0.0149"/>
  <xacro:property name="d435_glass_to_front" value="0.1e-3"/>
  <xacro:property name="d435_zero_depth_to_glass" value="4.2e-3"/>
  <xacro:property name="d435_mesh_x_offset" value="${d435_cam_mount_from_center_offset-d435_glass_to_front-d435_zero_depth_to_glass}"/>
  <xacro:property name="d435_cam_depth_px" value="${d435_cam_mount_from_center_offset}"/>
  <xacro:property name="d435_cam_depth_py" value="0.0175"/>
  <xacro:property name="d435_cam_depth_pz" value="${d435_cam_height/2}"/>

  <xacro:property name="camera_width" value="1280"/>
  <xacro:property name="camera_height" value="720"/>
  <xacro:property name="camera_fps" value="30"/>
  <xacro:property name="horizontal_fov" value="${69.4 * M_PI / 180}"/>
  <xacro:property name="rgb_horizontal_fov" value="${69.4 * M_PI / 180}"/>
  <xacro:property name="depth_horizontal_fov" value="${85.2 * M_PI / 180}"/>


  <xacro:macro name="camera" params="
    parent
    sim_gazebo
    sim_ignition
    sim_isaac">

    <xacro:if value="${sim_isaac}">
      <joint name="${parent}_depth_joint" type="fixed">
        <origin xyz="${d435_cam_mount_from_center_offset + d435_zero_depth_to_glass - d435_cam_depth} ${d435_cam_depth_py} 0" rpy="0 0 0"/>
        <parent link="${parent}"/>
        <child link="${parent}_depth_frame" />
      </joint>
      <link name="${parent}_depth_frame">
        <inertial>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <mass value="0.01"/>
          <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
        </inertial>
        <visual>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </collision>
      </link>
    </xacro:if>
    
    <xacro:if value="${sim_gazebo or sim_ignition}">
      <joint name="${parent}_depth_joint" type="fixed">
        <origin xyz="${d435_cam_mount_from_center_offset + d435_zero_depth_to_glass - d435_cam_depth} ${d435_cam_depth_py} 0" rpy="0 0 0"/>
        <parent link="${parent}"/>
        <child link="${parent}_depth_frame" />
      </joint>
      <link name="${parent}_depth_frame">
        <inertial>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <mass value="0.01"/>
          <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
        </inertial>
        <visual>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </collision>
      </link>

      <joint name="${parent}_depth_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${parent}_depth_frame" />
        <child link="${parent}_depth_optical_frame" />
      </joint>
      <link name="${parent}_depth_optical_frame">
        <inertial>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <mass value="0.01"/>
          <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
        </inertial>
        <visual>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </collision>
      </link>

      <joint name="${parent}_infra1_joint" type="fixed">
        <origin xyz="0 ${d435_cam_depth_to_infra1_offset} 0" rpy="0 0 0" />
        <parent link="${parent}_depth_frame" />
        <child link="${parent}_infra1_frame" />
      </joint>
      <link name="${parent}_infra1_frame">
        <inertial>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <mass value="0.01"/>
          <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
        </inertial>
        <visual>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </collision>
      </link>

      <joint name="${parent}_infra1_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${parent}_infra1_frame" />
        <child link="${parent}_infra1_optical_frame" />
      </joint>
      <link name="${parent}_infra1_optical_frame">
        <inertial>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <mass value="0.01"/>
          <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
        </inertial>
        <visual>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </collision>
      </link>

      <joint name="${parent}_infra2_joint" type="fixed">
        <origin xyz="0 ${d435_cam_depth_to_infra2_offset} 0" rpy="0 0 0" />
        <parent link="${parent}_depth_frame" />
        <child link="${parent}_infra2_frame" />
      </joint>
      <link name="${parent}_infra2_frame">
        <inertial>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <mass value="0.01"/>
          <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
        </inertial>
        <visual>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </collision>
      </link>

      <joint name="${parent}_infra2_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${parent}_infra2_frame" />
        <child link="${parent}_infra2_optical_frame" />
      </joint>
      <link name="${parent}_infra2_optical_frame">
        <inertial>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <mass value="0.01"/>
          <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
        </inertial>
        <visual>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </collision>
      </link>

      <joint name="${parent}_color_joint" type="fixed">
        <origin xyz="0 ${d435_cam_depth_to_color_offset} 0" rpy="0 0 0" />
        <parent link="${parent}_depth_frame" />
        <child link="${parent}_color_frame" />
      </joint>
      <link name="${parent}_color_frame">
        <inertial>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <mass value="0.01"/>
          <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
        </inertial>
        <visual>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </collision>
      </link>

      <joint name="${parent}_color_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${parent}_color_frame" />
        <child link="${parent}_color_optical_frame" />
      </joint>
      <link name="${parent}_color_optical_frame">
        <inertial>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <mass value="0.01"/>
          <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
        </inertial>
        <visual>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </collision>
      </link>


      <joint name="${parent}_accel_joint" type="fixed">
        <origin xyz = "-0.01174 -0.00552 0.0051" rpy = "0 0 0" />
        <parent link="${parent}_depth_frame" />
        <child link="${parent}_accel_frame" />
      </joint>
      <link name="${parent}_accel_frame">
        <inertial>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <mass value="0.01"/>
          <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
        </inertial>
        <visual>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </collision>
      </link>

      <joint name="${parent}_accel_optical_joint" type="fixed">
        <origin xyz = "0 0 0" rpy = "${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${parent}_accel_frame" />
        <child link="${parent}_accel_optical_frame" />
      </joint>
      <link name="${parent}_accel_optical_frame">
        <inertial>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <mass value="0.01"/>
          <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
        </inertial>
        <visual>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </collision>
      </link>

      <joint name="${parent}_gyro_joint" type="fixed">
        <origin xyz = "-0.01174 -0.00552 0.0051" rpy = "0 0 0" />
        <parent link="${parent}_depth_frame" />
        <child link="${parent}_gyro_frame" />
      </joint>
      <link name="${parent}_gyro_frame">
        <inertial>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <mass value="0.01"/>
          <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
        </inertial>
        <visual>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </collision>
      </link>

      <joint name="${parent}_gyro_optical_joint" type="fixed">
        <origin xyz = "0 0 0" rpy = "${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${parent}_gyro_frame" />
        <child link="${parent}_gyro_optical_frame" />
      </joint>
      <link name="${parent}_gyro_optical_frame">
        <inertial>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <mass value="0.01"/>
          <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
        </inertial>
        <visual>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <sphere radius="0.001"/>
          </geometry>
        </collision>
      </link>
    </xacro:if>

    <xacro:if value="${sim_gazebo}">
      <gazebo reference="${parent}">
        <sensor name="${parent}_realsense" type="multi_camera">
          <update_rate>${camera_fps}</update_rate>
          <always_on>1</always_on>
          <visualize>true</visualize>
          <plugin name="gazebo_ros_realsense_camera" filename="libgazebo_ros_realsense_camera.so">
            <depth_topic>depth/image_raw</depth_topic>
            <infra1_topic>infra1/image_raw</infra1_topic>
            <infra2_topic>infra2/image_raw</infra2_topic>
            <color_topic>color/image_raw</color_topic>
            <depth_camera_info_topic>depth/camera_info</depth_camera_info_topic>
            <infra1_camera_info_topic>infra1/camera_info</infra1_camera_info_topic>
            <infra2_camera_info_topic>infra2/camera_info</infra2_camera_info_topic>
            <color_camera_info_topic>color/camera_info</color_camera_info_topic>
            <point_cloud_topic>depth/points</point_cloud_topic>
            <enable_point_cloud>true</enable_point_cloud>
            <point_cloud_cutoff>0.5</point_cloud_cutoff>
            <range_min>0.1</range_min>
            <range_max>10.0</range_max>
            <robot_namespace>${parent}</robot_namespace>
            <depth_frame_name>${parent}_depth_optical_frame</depth_frame_name>
            <infra1_frame_name>${parent}_infra1_optical_frame</infra1_frame_name>
            <infra2_frame_name>${parent}_infra2_optical_frame</infra2_frame_name>
            <color_frame_name>${parent}_color_optical_frame</color_frame_name>
          </plugin>
          <!-- 깊이 카메라 설정 -->
          <camera name="depth">
            <horizontal_fov>${depth_horizontal_fov}</horizontal_fov>
            <image>
              <width>${camera_width}</width>
              <height>${camera_height}</height>
              <format>R8G8B8</format>
            </image>
            <clip>
              <near>0.1</near>
              <far>10.0</far>
            </clip>
          </camera>
          <!-- 컬러 카메라 설정 -->
          <camera name="color">
            <horizontal_fov>${rgb_horizontal_fov}</horizontal_fov>
            <image>
              <width>${camera_width}</width>
              <height>${camera_height}</height>
              <format>R8G8B8</format>
            </image>
            <clip>
              <near>0.1</near>
              <far>10.0</far>
            </clip>
          </camera>
          <!-- 적외선 카메라 설정 -->
          <camera name="infra1">
            <horizontal_fov>${depth_horizontal_fov}</horizontal_fov>
            <image>
              <width>${camera_width}</width>
              <height>${camera_height}</height>
              <format>L8</format>
            </image>
            <clip>
              <near>0.1</near>
              <far>10.0</far>
            </clip>
          </camera>
          <camera name="infra2">
            <horizontal_fov>${depth_horizontal_fov}</horizontal_fov>
            <image>
              <width>${camera_width}</width>
              <height>${camera_height}</height>
              <format>L8</format>
            </image>
            <clip>
              <near>0.1</near>
              <far>10.0</far>
            </clip>
          </camera>
        </sensor>
      </gazebo>
    </xacro:if>

    <xacro:if value="${sim_ignition}">
      <gazebo reference="${parent}_depth_frame">
        <sensor name="${parent}_depth_sensor" type="depth_camera">
          <always_on>1</always_on>
          <update_rate>${camera_fps}</update_rate>
          <visualize>true</visualize>
          <topic>${parent}/depth/image_raw</topic>
          <camera>
            <horizontal_fov>${depth_horizontal_fov}</horizontal_fov>
            <image>
              <width>${camera_width}</width>
              <height>${camera_height}</height>
              <format>R_FLOAT32</format>
            </image>
            <clip>
              <near>0.1</near>
              <far>10.0</far>
            </clip>
          </camera>
          <plugin filename="libignition-gazebo-sensors-system.so" name="ignition::gazebo::systems::Sensors"/>
        </sensor>
      </gazebo>

      <gazebo reference="${parent}_color_frame">
        <sensor name="${parent}_rgb_sensor" type="camera">
          <always_on>1</always_on>
          <update_rate>${camera_fps}</update_rate>
          <visualize>true</visualize>
          <topic>${parent}/color/image_raw</topic>
          <camera>
            <horizontal_fov>${rgb_horizontal_fov}</horizontal_fov>
            <image>
              <width>${camera_width}</width>
              <height>${camera_height}</height>
              <format>R8G8B8</format>
            </image>
            <clip>
              <near>0.1</near>
              <far>10.0</far>
            </clip>
          </camera>
          <plugin filename="libignition-gazebo-sensors-system.so" name="ignition::gazebo::systems::Sensors"/>
        </sensor>
      </gazebo>

      <gazebo reference="${parent}_infra1_frame">
        <sensor name="${parent}_infra1_sensor" type="camera">
          <always_on>1</always_on>
          <update_rate>${camera_fps}</update_rate>
          <visualize>false</visualize>
          <topic>${parent}/infra1/image_raw</topic>
          <camera>
            <horizontal_fov>${depth_horizontal_fov}</horizontal_fov>
            <image>
              <width>${camera_width}</width>
              <height>${camera_height}</height>
              <format>L8</format>
            </image>
            <clip>
              <near>0.1</near>
              <far>10.0</far>
            </clip>
          </camera>
          <plugin filename="libignition-gazebo-sensors-system.so" name="ignition::gazebo::systems::Sensors"/>
        </sensor>
      </gazebo>

      <gazebo reference="${parent}_infra2_frame">
        <sensor name="${parent}_infra2_sensor" type="camera">
          <always_on>1</always_on>
          <update_rate>${camera_fps}</update_rate>
          <visualize>false</visualize>
          <topic>${parent}/infra2/image_raw</topic>
          <camera>
            <horizontal_fov>${depth_horizontal_fov}</horizontal_fov>
            <image>
              <width>${camera_width}</width>
              <height>${camera_height}</height>
              <format>L8</format>
            </image>
            <clip>
              <near>0.1</near>
              <far>10.0</far>
            </clip>
          </camera>
          <plugin filename="libignition-gazebo-sensors-system.so" name="ignition::gazebo::systems::Sensors"/>
        </sensor>
      </gazebo>

      <gazebo reference="${parent}_accel_frame">
        <sensor name="${parent}_imu_sensor" type="imu">
          <always_on>1</always_on>
          <update_rate>${camera_fps}</update_rate>
          <visualize>false</visualize>
          <topic>${parent}/imu/data</topic>
          <imu>
            <angular_velocity>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>0.0001</stddev>
              </noise>
            </angular_velocity>
            <linear_acceleration>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>0.00098</stddev>
              </noise>
            </linear_acceleration>
          </imu>
          <plugin filename="libignition-gazebo-sensors-system.so" name="ignition::gazebo::systems::Sensors"/>
        </sensor>
      </gazebo>
    </xacro:if>
  </xacro:macro>
</robot>