<?xml version="1.0"?>

<robot name="kinova_arm" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="M_PI" value="3.14159265358979323846" />
  <xacro:property name="base_body_width" value="0.4" />
  <xacro:property name="base_body_length" value="0.4" />
  <xacro:property name="total_height" value="0.29386" />
  <xacro:property name="front_wheel_length" value="0.127547" />
  <xacro:property name="front_wheel_radius" value="0.0575" />
  <xacro:property name="front_wheel_depth" value="0.079536242431022" />
  <xacro:property name="rear_wheel_length" value="0.125" />
  <xacro:property name="rear_wheel_radius" value="0.0325" />
  <xacro:property name="rear_wheel_depth" value="0.022335230282742743" />

  <xacro:property name="base_body_mass" value="24.3948952632956" />
  <xacro:property name="front_wheel_mass" value="1.0568406891164" />
  <xacro:property name="rear_wheel_bracket_mass" value="0.0211573699864" />
  <xacro:property name="rear_wheel_mass" value="0.0920111896829" />
  <xacro:property name="camera_mass" value="0.2333248928640" />
  <xacro:property name="lidar_mass" value="0.1071556446529" />
  <xacro:property name="base_arm_connector_mass" value="0.4535071053510" />
  <!-- Include inertial xacro files -->
  <xacro:include filename="$(find mobile_manipulator)/urdf/inertial.xacro" />
	<xacro:macro name="load_model" params="
    vision
    robot_ip
    username
    password
    port
    port_realtime
    session_inactivity_timeout_ms
    connection_inactivity_timeout_ms
    use_internal_bus_gripper_comm
    use_fake_hardware
    fake_sensor_commands
    sim_gazebo
    sim_ignition
    sim_isaac
    gripper_joint_name
    gripper_max_velocity
    gripper_max_force
    isaac_joint_commands
    isaac_joint_states
    initial_value">

    <!-- Ros2 Control Include -->
    <xacro:include filename="$(find mobile_manipulator)/urdf/integrate_ros2_control.xacro" />
      <xacro:mobile_manipulator_control
        use_fake_hardware="${use_fake_hardware}"
        fake_sensor_commands="${fake_sensor_commands}"
        sim_gazebo="${sim_gazebo}"
        sim_ignition="${sim_ignition}"
        sim_isaac="${sim_isaac}"
        isaac_joint_commands="${isaac_joint_commands}"
        isaac_joint_states="${isaac_joint_states}"
        initial_value="${initial_value}"/>


    <link name="base_link"/>
    <joint name="base_body_joint" type="fixed">
      <origin xyz="0 0 ${total_height}" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="base_body" />
      <axis xyz="0 0 0" />
    </joint>
    <link name="base_body">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/base/base_body.stl" />
        </geometry>
        <material name="">
          <color rgba="1 1 1 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/base/base_body.stl" />
        </geometry>
      </collision>
      <xacro:inertial_box mass="${base_body_mass}" x="0.4" y="0.4" z="0.26344">
        <origin xyz="0 0 0" rpy="0 0 0" />
      </xacro:inertial_box>
    </link>

    <joint name="fl_joint" type="continuous">
      <origin xyz="0.05 ${front_wheel_length} ${front_wheel_radius - total_height} " rpy="-${M_PI / 2} 0 0"/>
      <parent link="base_body" />
      <child link="fl_wheel" />
      <axis xyz="0 0 1" />
    </joint>
    <link name="fl_wheel">
      <visual>
        <origin rpy="${M_PI/2} 0 0" xyz="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/base/front_wheel.stl" />
        </geometry>
        <material name="">
          <color rgba="0.5 0.5 0.5 1" />
        </material>
      </visual>
      <collision>
        <origin rpy="${M_PI/2} 0 0" xyz="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/base/front_wheel.stl" />
        </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${front_wheel_mass}" length="${front_wheel_depth}" radius="${front_wheel_radius}">
        <origin rpy="${M_PI/2} 0 0" xyz="0 0 0" />
      </xacro:inertial_cylinder>
    </link>


    <joint name="fr_joint" type="continuous">
      <origin xyz="0.05 -${front_wheel_length} ${front_wheel_radius - total_height}" rpy="${M_PI/2} 0 0" />
      <parent link="base_body" />
      <child link="fr_wheel" />
      <axis xyz="0 0 1" />
    </joint>
    <link name="fr_wheel">
      <visual>
        <origin rpy="-${M_PI/2} 0 0" xyz="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/base/front_wheel.stl" />
        </geometry>
        <material name="">
          <color rgba="0.5 0.5 0.5 1" />
        </material>
      </visual>
      <collision>
        <origin rpy="-${M_PI/2} 0 0" xyz="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/base/front_wheel.stl" />
        </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${front_wheel_mass}" length="${front_wheel_depth}" radius="${front_wheel_radius}">
        <origin rpy="-${M_PI/2} 0 0" xyz="0 0 0" />
      </xacro:inertial_cylinder>
    </link>

    <joint name="rl_bracket_joint" type="continuous">
      <origin xyz="-0.17043 ${rear_wheel_length} ${rear_wheel_radius - total_height + 0.0453}" rpy="0 0 0" />
      <parent link="base_body" />
      <child link="rl_bracket" />
      <axis xyz="0 0 1" />
    </joint>
    <link name="rl_bracket">
      <visual>
        <origin rpy="0 0 ${M_PI/2}" xyz="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/base/rear_wheel_bracket.stl" />
        </geometry>
        <material name="">
          <color rgba="0.5 0.5 0.5 1" />
        </material>
      </visual>
      <collision>
        <origin rpy="0 0 ${M_PI/2}" xyz="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/base/rear_wheel_bracket.stl" />
        </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${rear_wheel_bracket_mass}" length="0.0453" radius="0.01">
        <origin rpy="0 0 ${M_PI/2}" xyz="0 0 0" />
      </xacro:inertial_cylinder>
    </link>


    <joint name="rl_wheel_joint" type="continuous">
      <origin xyz="-0.027 0 -0.0453" rpy="-${M_PI/2} 0 0" />
      <parent link="rl_bracket" />
      <child link="rl_wheel" />
      <axis xyz="0 0 1" />
    </joint>
    <link name="rl_wheel">
      <visual>
        <origin rpy="0 -${M_PI/2} 0" xyz="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/base/rear_wheel.stl" />
        </geometry>
        <material name="">
          <color rgba="0.5 0.5 0.5 1" />
        </material>
      </visual>
      <collision>
        <origin rpy="0 -${M_PI/2} 0" xyz="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/base/rear_wheel.stl" />
        </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${rear_wheel_mass}" length="${rear_wheel_depth}" radius="${rear_wheel_radius}">
        <origin rpy="0 -${M_PI/2} 0" xyz="0 0 0" />
      </xacro:inertial_cylinder>
    </link>


    <joint name="rr_bracket_joint" type="continuous">
      <origin xyz="-0.17043 -${rear_wheel_length} ${rear_wheel_radius - total_height + 0.0453}" rpy="0 0 0" />
      <parent link="base_body" />
      <child link="rr_bracket" />
      <axis xyz="0 0 1" />
    </joint>
    <link name="rr_bracket">
      <visual>
        <origin rpy="0 0 ${M_PI/2}" xyz="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/base/rear_wheel_bracket.stl" />
        </geometry>
        <material name="">
          <color rgba="0.5 0.5 0.5 1" />
        </material>
      </visual>
      <collision>
        <origin rpy="0 0 ${M_PI/2}" xyz="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/base/rear_wheel_bracket.stl" />
        </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${rear_wheel_bracket_mass}" length="0.0453" radius="0.01">
        <origin rpy="0 0 ${M_PI/2}" xyz="0 0 0" />
      </xacro:inertial_cylinder>
    </link>

    <joint name="rr_wheel_joint" type="continuous">
      <origin xyz="-0.027 0 -0.0453" rpy="${M_PI/2} 0 0" />
      <parent link="rr_bracket" />
      <child link="rr_wheel" />
      <axis xyz="0 0 1" />
    </joint>
    <link name="rr_wheel">
      <visual>
        <origin rpy="0 ${M_PI/2} 0" xyz="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/base/rear_wheel.stl" />
        </geometry>
        <material name="">
          <color rgba="0.5 0.5 0.5 1" />
        </material>
      </visual>
      <collision>
        <origin rpy="0 ${M_PI/2} 0" xyz="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/base/rear_wheel.stl" />
        </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${rear_wheel_mass}" length="${rear_wheel_depth}" radius="${rear_wheel_radius}">
        <origin rpy="0 ${M_PI/2} 0" xyz="0 0 0" />
      </xacro:inertial_cylinder>
    </link>

    
    <joint name="laser_joint" type="fixed">
      <origin xyz="0.04517 0 -0.1053" rpy="0 0 0" />
      <parent link="base_body" />
      <child link="laser_Link" />
      <axis xyz="0 0 0" />
    </joint>
    <link name="laser_Link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/base/lidar.stl" />
        </geometry>
        <material name="">
          <color rgba="1 0.6 0 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/base/lidar.stl" />
        </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${lidar_mass}" length="0.02" radius="0.0389">
        <origin xyz="0 0 0" rpy="0 0 0" />
      </xacro:inertial_cylinder>
    </link>
    

    <joint name="camera_joint" type="fixed">
      <origin xyz="0.115 0 -0.04565" rpy="0 0 0" />
      <parent link="base_body" />
      <child link="camera_link" />
      <axis xyz="0 0 0" />
    </joint>
    <link name="camera_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/base/camera.stl" />
        </geometry>
        <material name="">
          <color rgba="0.79216 0.81961 0.93333 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/base/camera.stl" />
        </geometry>
      </collision>
      <xacro:inertial_cylinder mass="${camera_mass}" length="0.08832" radius="0.01265">
        <origin xyz="0 0 0" rpy="-${M_PI/2} 0 0" />
      </xacro:inertial_cylinder>
    </link>


    <joint name="base_arm_connector_joint" type="fixed">
      <origin xyz="0 0 0.0576" rpy="0 0 0" />
      <parent link="base_body" />
      <child link="base_arm_connector"/>
      <axis xyz="0 0 0" />
    </joint>
    <link name="base_arm_connector">
      <visual>
        <origin xyz="0 0 -0.0288" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/base/base_arm_connector.stl" />
        </geometry>
        <material name="">
          <color rgba="0.79216 0.81961 0.93333 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 -0.0288" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/base/base_arm_connector.stl" />
        </geometry>
      </collision>
      <xacro:inertial_truncated_cone mass="${base_arm_connector_mass}" r1="0.03697" r2="0.05137" height="0.0576">
        <origin xyz="0 0 -0.0288" rpy="0 0 0" />
      </xacro:inertial_truncated_cone>
    </link>
    <gazebo reference="base_arm_connector">
        <material>Kortex/Gray</material>
    </gazebo>


    <joint name="arm_base_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_arm_connector" />
      <child link="arm_base_link" />
    </joint>
    <link name="arm_base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/arm/base_link.STL" />
        </geometry>
        <material name="">
          <color rgba="0.803 0.824 0.820 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/arm/base_link.STL" />
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0.00244324 0.00015573 0.08616742" rpy="0 0 0" />
        <mass value="1.14608471" />
        <inertia ixx="0.00335854" ixy="3.9E-07" ixz="0.00010989" iyy="0.003311" iyz="1.91E-06" izz="0.00077158" />
      </inertial>
    </link>
    <gazebo reference="arm_base_link">
      <material>Kortex/Gray</material>
    </gazebo>


		<joint name="arm_joint_1" type="revolute">
      <origin xyz="0 0 0.12825" rpy="0 0 0" />
      <parent link="arm_base_link" />
      <child link="arm_link_1" />
      <axis xyz="0 0 1" />
      <limit lower="-2.69" upper="2.69" effort="10" velocity="1.6" />
    </joint>    
    <link name="arm_link_1">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/arm/shoulder_link.STL" />
        </geometry>
        <material name="">
          <color rgba="0.803 0.824 0.820 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/arm/shoulder_link.STL" />
        </geometry>
      </collision>
      <inertial>
        <origin xyz="2.477E-05 0.02213531 0.09937686" rpy="0 0 0" />
        <mass value="0.95974404" />
        <inertia ixx="0.00165947" ixy="2E-08" ixz="3.6E-07" iyy="0.00140355" iyz="0.00034927" izz="0.00089493" />
      </inertial>
    </link>
    <gazebo reference="arm_link_1">
      <material>Kortex/Gray</material>
    </gazebo>


		<joint name="arm_joint_2" type="revolute">
      <origin xyz="0 -0.03 0.115" rpy="1.5708 0 0" />
      <parent link="arm_link_1" />
      <child link="arm_link_2" />
      <axis xyz="0 0 1" />
      <limit lower="-2.69" upper="2.69" effort="14" velocity="1.6" />
    </joint>
    <link name="arm_link_2">
      <inertial>
        <origin xyz="0.02998299 0.21154808 0.0453031" rpy="0 0 0" />
        <mass value="1.17756164" />
        <inertia ixx="0.01149277" ixy="1E-06" ixz="1.6E-07" iyy="0.00102851" iyz="0.00140765" izz="0.01133492" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/arm/arm_link.STL" />
        </geometry>
        <material name="">
          <color rgba="0.803 0.824 0.820 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/arm/arm_link.STL" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="arm_link_2">
      <material>Kortex/Gray</material>
    </gazebo>

		
    <joint name="arm_joint_3" type="revolute">
      <origin xyz="0 0.28 0" rpy="-3.1416 0 0" />
      <parent link="arm_link_2" />
      <child link="arm_link_3" />
      <axis xyz="0 0 1" />
      <limit lower="-2.69" upper="2.69" effort="10" velocity="1.6" />
    </joint>
    <link name="arm_link_3">
      <inertial>
        <origin xyz="0.0301559 0.09502206 0.0073555" rpy="0 0 0" />
        <mass value="0.59767669" />
        <inertia ixx="0.00163256" ixy="7.11E-06" ixz="1.54E-06" iyy="0.00029798" iyz="9.587E-05" izz="0.00169091" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/arm/forearm_link.STL" />
        </geometry>
        <material name="">
          <color rgba="0.803 0.824 0.820 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/arm/forearm_link.STL" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="arm_link_3">
      <material>Kortex/Gray</material>
    </gazebo>


		<joint name="arm_joint_4" type="revolute">
      <origin xyz="0 -0.14 0.02" rpy="1.5708 0 0" />
      <parent link="arm_link_3" />
      <child link="arm_link_4" />
      <axis xyz="0 0 1" />
      <limit lower="-2.59" upper="2.59" effort="7" velocity="1.6" />
    </joint>
    <link name="arm_link_4">
      <inertial>
        <origin xyz="0.00575149 0.01000443 0.08719207" rpy="0 0 0" />
        <mass value="0.52693412" />
        <inertia ixx="0.00069098" ixy="2.4E-07" ixz="0.00016483" iyy="0.00078519" iyz="7.4E-07" izz="0.00034115" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/arm/lower_wrist_link.STL" />
        </geometry>
        <material name="">
          <color rgba="0.803 0.824 0.820 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/arm/lower_wrist_link.STL" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="arm_link_4">
      <material>Kortex/Gray</material>
    </gazebo>


		<joint name="arm_joint_5" type="revolute">
      <origin xyz="0.0285 0 0.105" rpy="0 1.5708 0" />
      <parent link="arm_link_4" />
      <child link="arm_link_5" />
      <axis xyz="0 0 1" />
      <limit lower="-2.57" upper="2.57" effort="7" velocity="1.6" />
    </joint>
    <link name="arm_link_5">
      <inertial>
        <origin xyz="0.08056517 0.00980409 0.01872799" rpy="0 0 0" />
        <mass value="0.58097325" />
        <inertia ixx="0.00021268" ixy="5.21E-06" ixz="2.91E-06" iyy="0.00106371" iyz="1.1E-07" izz="0.00108465" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/arm/upper_wrist_link.STL" />
        </geometry>
        <material name="">
          <color rgba="0.803 0.824 0.820 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/arm/upper_wrist_link.STL" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="arm_link_5">
      <material>Kortex/Gray</material>
    </gazebo>


		<joint name="arm_joint_6" type="revolute">
      <origin xyz="-0.105 0 0.0285" rpy="0 -1.5708 0" />
      <parent link="arm_link_5" />
      <child link="end_effector_link" />
      <axis xyz="0 0 1" />
      <limit lower="-2.59" upper="2.59" effort="7" velocity="3.2" />
    </joint>
    <link name="end_effector_link"/>


    <joint name="tool_frame_joint" type="fixed">
        <origin xyz="0 0 0.130" rpy="0 0 1.57079632679" />
        <parent link="end_effector_link" />
        <child link="tool_frame" />
        <axis xyz="0 0 0" />
    </joint>
    <link name="tool_frame"/>


		<joint name="gripper_base_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="end_effector_link" />
      <child link="gripper_base_link" />
      <axis xyz="0 0 0" />
    </joint>
		<link name="gripper_base_link">
      <inertial>
        <origin xyz="4.03E-06 1.08E-05 0.041397" rpy="0 0 0" />
        <mass value="0.1395" />
        <inertia ixx="0.00011614" ixy="1E-08" ixz="4E-08" iyy="0.00010327" iyz="0" izz="9.707E-05" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/gripper/gripper_base_link.STL" />
        </geometry>
        <material name="">
          <color rgba="0.803 0.824 0.820 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/gripper/gripper_base_link.STL" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="gripper_base_link">
      <material>Kortex/Gray</material>
    </gazebo>


		<joint name="right_finger_bottom_joint" type="revolute">
      <origin xyz="0 -0.030501 0.070003" rpy="1.571 0.611 1.571" />
      <parent link="gripper_base_link" />
      <child link="right_finger_prox_link" />
      <axis xyz="0 0 -1" />
      <limit lower="0.0" upper="0.85" effort="50" velocity="0.6" />
    </joint>
    <link name="right_finger_prox_link">
      <inertial>
        <origin xyz="0.020257 0.0063483 6.991E-05" rpy="0 0 0" />
        <mass value="0.018385" />
        <inertia ixx="2.29E-06" ixy="1.43E-06" ixz="0" iyy="4.56E-06" iyz="0" izz="4.77E-06" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/gripper/right_finger_prox_link.STL" />
        </geometry>
        <material name="">
            <color rgba="0.803 0.824 0.820 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/gripper/right_finger_prox_link.STL" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="right_finger_prox_link">
      <material>Kortex/Gray</material>
    </gazebo>


		<joint name="right_finger_tip_joint" type="revolute">
      <origin xyz="-0.045636 0.020423 0" rpy="0 0 0" />
      <parent link="right_finger_prox_link" />
      <child link="right_finger_dist_link" />
      <axis xyz="0 0 1" />
      <limit lower="-0.50" upper="0.21" effort="1000" velocity="1000" /> <!--limit lower="-1.03" upper="0.21" effort="1000" velocity="1000" /-->
      <mimic joint="right_finger_bottom_joint" multiplier="-0.676" offset="0.149" />
    </joint>
    <link name="right_finger_dist_link">
      <inertial>
        <origin xyz="0.018488 0.0011091 0" rpy="0 0 0" />
        <mass value="0.010748" />
        <inertia ixx="6.3E-07" ixy="3.2E-07" ixz="0" iyy="1.83E-06" iyz="0" izz="1.61E-06" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/gripper/right_finger_dist_link.STL" />
        </geometry>
        <material name="">
          <color rgba="0 0.055 0.525 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/gripper/right_finger_dist_link.STL" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="right_finger_dist_link">
      <material>Kortex/Blue</material>
    </gazebo>


		<joint name="left_finger_bottom_joint" type="revolute">
      <origin xyz="0 0.0305 0.070003" rpy="-1.571 0.611 -1.571" />
      <parent link="gripper_base_link" />
      <child link="left_finger_prox_link" />
      <axis xyz="0 0 1" />
      <limit lower="0.0" upper="0.85" effort="1000" velocity="1000" />
      <mimic joint="right_finger_bottom_joint" multiplier="1.0" offset="0.0" />
    </joint>
    <link name="left_finger_prox_link">
      <inertial>
        <origin xyz="0.020257 0.0063483 6.99E-05" rpy="0 0 0" />
        <mass value="0.018385" />
        <inertia ixx="2.29E-06" ixy="1.43E-06" ixz="0" iyy="4.56E-06" iyz="0" izz="4.77E-06" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/gripper/left_finger_prox_link.STL" />
        </geometry>
        <material name="">
          <color rgba="0.803 0.824 0.820 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/gripper/left_finger_prox_link.STL" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="left_finger_prox_link">
      <material>Kortex/Gray</material>
    </gazebo>
    
    
    <joint name="left_finger_tip_joint" type="revolute">
      <origin xyz="-0.045636 -0.020423 6.9901E-05" rpy="0 0 0" />
      <parent link="left_finger_prox_link" />
      <child link="left_finger_dist_link" />
      <axis xyz="0 0 -1" />
      <limit lower="-0.50" upper="0.21" effort="1000" velocity="1000" /> <!--limit lower="-1.03" upper="0.21" effort="1000" velocity="1000" /-->
      <mimic joint="right_finger_bottom_joint" multiplier="-0.676" offset="0.149" />
    </joint>
    <link name="left_finger_dist_link">
      <inertial>
        <origin xyz="-0.018488 0.0011091 0" rpy="0 0 0" />
        <mass value="0.010748" />
        <inertia ixx="6.3E-07" ixy="3.2E-07" ixz="0" iyy="1.83E-06" iyz="0" izz="1.61E-06" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/gripper/left_finger_dist_link.STL" />
        </geometry>
        <material name="">
          <color rgba="0 0.055 0.525 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobile_manipulator/meshes/gripper/left_finger_dist_link.STL" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="left_finger_dist_link">
      <material>Kortex/Blue</material>
    </gazebo>
  </xacro:macro>
</robot>

